import React, { useState } from 'react';
import { Button } from '../ui/Button';
import { Sparkles, ArrowRight, Target, AlertTriangle, Check } from 'lucide-react';

export const IdeaValidator = () => {
    const [step, setStep] = useState<'input' | 'analyzing' | 'results'>('input');
    const [idea, setIdea] = useState({ name: '', problem: '', solution: '', audience: '' });

    const handleAnalyze = () => {
        setStep('analyzing');
        // Mock API call delay
        setTimeout(() => {
            setStep('results');
        }, 2000);
    };

    if (step === 'input') {
        return (
            <div className="max-w-2xl mx-auto">
                <div className="text-center mb-8">
                    <h2 className="text-3xl font-bold text-white mb-2">Validate Your Next Big Idea</h2>
                    <p className="text-zinc-400">AI-powered market analysis and feasibility scoring.</p>
                </div>

                <div className="bg-dark-surface border border-white/5 p-5 sm:p-8 rounded-2xl space-y-6">
                    <div>
                        <label className="block text-sm font-medium text-zinc-400 mb-2">Project Name</label>
                        <input
                            className="w-full bg-zinc-800/50 border border-zinc-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                            placeholder="e.g. Uber for Cats"
                            value={idea.name}
                            onChange={(e) => setIdea({ ...idea, name: e.target.value })}
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-zinc-400 mb-2">Target Audience</label>
                        <input
                            className="w-full bg-zinc-800/50 border border-zinc-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                            placeholder="e.g. Busy cat owners in urban areas"
                            value={idea.audience}
                            onChange={(e) => setIdea({ ...idea, audience: e.target.value })}
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-zinc-400 mb-2">Problem Statement</label>
                        <textarea
                            className="w-full bg-zinc-800/50 border border-zinc-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-brand-500/50 h-32 resize-none"
                            placeholder="What pain point are you solving?"
                            value={idea.problem}
                            onChange={(e) => setIdea({ ...idea, problem: e.target.value })}
                        />
                    </div>

                    <Button variant="primary" className="w-full py-4 text-lg" onClick={handleAnalyze}>
                        <Sparkles className="w-5 h-5 mr-2" />
                        Analyze Feasibility
                    </Button>
                </div>
            </div>
        );
    }

    if (step === 'analyzing') {
        return (
            <div className="min-h-[60vh] flex flex-col items-center justify-center text-center">
                <div className="relative w-24 h-24 mb-8">
                    <div className="absolute inset-0 border-4 border-brand-500/30 rounded-full animate-pulse"></div>
                    <div className="absolute inset-0 border-t-4 border-brand-400 rounded-full animate-spin"></div>
                    <Sparkles className="absolute inset-0 m-auto w-8 h-8 text-white animate-bounce" />
                </div>
                <h3 className="text-2xl font-bold text-white mb-2">Crunching the numbers...</h3>
                <p className="text-zinc-400">Analyzing market trends, competition, and viability.</p>
            </div>
        );
    }

    return (
        <div className="space-y-8 animate-fade-in">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-3xl font-bold text-white mb-2">Analysis Results: {idea.name}</h2>
                    <p className="text-zinc-400">Generated by CoLab AI Engine</p>
                </div>
                <Button variant="secondary" onClick={() => setStep('input')}>New Analysis</Button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                <ResultCard
                    title="Viability Score"
                    value="85/100"
                    desc="High potential, low barrier to entry."
                    color="text-green-400"
                    bg="bg-green-500/10"
                />
                <ResultCard
                    title="Market Size"
                    value="$4.2B"
                    desc="Growing at 12% CAGR globally."
                    color="text-blue-400"
                    bg="bg-blue-500/10"
                />
                <ResultCard
                    title="Competition"
                    value="Medium"
                    desc="3 major players detected."
                    color="text-orange-400"
                    bg="bg-orange-500/10"
                />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="bg-dark-surface border border-white/5 p-6 rounded-2xl">
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <Target className="w-5 h-5 text-brand-400" />
                        Strengths
                    </h3>
                    <ul className="space-y-3">
                        {['Strong niche appeal for urban demographic', 'Recurring revenue potential (subscription)', 'Low initial infrastructure implementation costs'].map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-zinc-300">
                                <Check className="w-5 h-5 text-green-400 shrink-0 mt-0.5" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>

                <div className="bg-dark-surface border border-white/5 p-6 rounded-2xl">
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <AlertTriangle className="w-5 h-5 text-red-400" />
                        Potential Risks
                    </h3>
                    <ul className="space-y-3">
                        {['High customer acquisition cost in early stages', 'Logistics of provider vetting', 'Seasonal demand fluctuations'].map((item, i) => (
                            <li key={i} className="flex items-start gap-3 text-zinc-300">
                                <ArrowRight className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
                                {item}
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
};

const ResultCard = ({ title, value, desc, color, bg }: any) => (
    <div className="bg-dark-surface border border-white/5 p-6 rounded-2xl">
        <p className="text-zinc-400 font-medium mb-2">{title}</p>
        <h4 className={`text-4xl font-bold mb-2 ${color}`}>{value}</h4>
        <div className={`inline-block px-3 py-1 rounded-full text-xs font-medium ${bg} ${color}`}>
            {desc}
        </div>
    </div>
);
